//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VERPSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrEmpAcademicProfileByAcademician
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string AssignmentToFieldOfStudy { get; set; }
        public string FoSArea { get; set; }
        public string FoSKnowledge { get; set; }
        public string FoSDiscipline { get; set; }
        public string Speciality { get; set; }
        public string PBNID { get; set; }
        public string NumberQuotedWoS { get; set; }
        public string IndexHirshaWoS { get; set; }
        public string Biogram { get; set; }
        public string ResearchInterests { get; set; }
        public string LecturedSubjects { get; set; }
        public string AbilityToTakeClasses { get; set; }
        public string GuestLectures { get; set; }
        public string ScientificHeldPositions { get; set; }
        public string OrganisationalHeldPositions { get; set; }
        public string ResearchActivities { get; set; }
        public Nullable<bool> HasConsultingExperience { get; set; }
        public string ConsultingSubjectArea { get; set; }
        public string ConsultingForm { get; set; }
        public Nullable<bool> PracticalActivistToHeldClass { get; set; }
        public Nullable<bool> CurrentPracticalActivist { get; set; }
        public Nullable<bool> UniversityActivity { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual hrPeople hrPeople { get; set; }
    }
}
