//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VERPSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrEmpAcademicProfileByHR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hrEmpAcademicProfileByHR()
        {
            this.hrEmpCourses = new HashSet<hrEmpCours>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public int Multiplier { get; set; }
        public string EmploymentBasis { get; set; }
        public string Degree { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public Nullable<bool> DoesScientificResearch { get; set; }
        public Nullable<int> PensumBilans { get; set; }
        public Nullable<int> ObligatoryWorkingHourOfPastYear { get; set; }
        public Nullable<int> DidacticPensum { get; set; }
        public Nullable<int> ScientificPensum { get; set; }
        public Nullable<int> OrganizationalPensum { get; set; }
        public string OtherArrangements { get; set; }
        public string OpinionAverage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public byte[] RowVersion { get; set; }
        public int hrEmpAcademicProfileByHR_erpFaculty { get; set; }
        public int hrEmpAcademicProfileByHR_erpPosition { get; set; }
        public int hrEmpAcademicProfileByHR_erpProgram { get; set; }
        public int hrEmpAcademicProfileByHR_erpUniversity { get; set; }
        public int hrEmpAcademicProfileByHR_hrPerson { get; set; }
        public int hrEmpAcademicProfileByHR_hrPerson1 { get; set; }
        public int hrEmpAcademicProfileByHR_hrPerson2 { get; set; }
        public int hrEmpAcademicProfileByHR_hrPerson3 { get; set; }
    
        public virtual erpFaculty erpFaculty { get; set; }
        public virtual erpPosition erpPosition { get; set; }
        public virtual erpProgram erpProgram { get; set; }
        public virtual erpUniversity erpUniversity { get; set; }
        public virtual hrPeople hrPeople { get; set; }
        public virtual hrPeople hrPeople1 { get; set; }
        public virtual hrPeople hrPeople2 { get; set; }
        public virtual hrPeople hrPeople3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpCours> hrEmpCourses { get; set; }
    }
}
