//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VERPSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrEmpProfile
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string NationalHealth { get; set; }
        public string IDType { get; set; }
        public string IDNumber { get; set; }
        public string IDIssuedBy { get; set; }
        public Nullable<System.DateTime> IDDate { get; set; }
        public string TaxOffice { get; set; }
        public string Street { get; set; }
        public string HouseNr { get; set; }
        public string FlatNr { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string NationalID { get; set; }
        public string ContactNumber { get; set; }
        public string BankAccount { get; set; }
        public Nullable<bool> HasPension { get; set; }
        public Nullable<System.DateTime> FirstPensionDate { get; set; }
        public string HighCostDeclarationCity { get; set; }
        public string ReceiveHighCostSeperationBenefit { get; set; }
        public string DontReceiveHighCostSeperationBenefit { get; set; }
        public Nullable<bool> IncomeTax1 { get; set; }
        public Nullable<bool> IncomeTax2 { get; set; }
        public Nullable<bool> IncomeTax3 { get; set; }
        public Nullable<bool> IncomeTax4 { get; set; }
        public Nullable<bool> IncomeTax5 { get; set; }
        public Nullable<bool> DeclerationOfTrueInformation { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public string Place { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public byte[] RowVersion { get; set; }
        public int hrEmpProfile_erpUniversity { get; set; }
    
        public virtual erpUniversity erpUniversity { get; set; }
        public virtual hrPeople hrPeople { get; set; }
    }
}
