//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VERPSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrPeople
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hrPeople()
        {
            this.erpAcademicDepartments = new HashSet<erpAcademicDepartment>();
            this.erpFaculties = new HashSet<erpFaculty>();
            this.erpUniversities = new HashSet<erpUniversity>();
            this.hrAddresses = new HashSet<hrAddress>();
            this.hrDepartments = new HashSet<hrDepartment>();
            this.hrEmergencyContacts = new HashSet<hrEmergencyContact>();
            this.hrEmpAcademicProfileByHRs = new HashSet<hrEmpAcademicProfileByHR>();
            this.hrEmpAcademicProfileByHRs1 = new HashSet<hrEmpAcademicProfileByHR>();
            this.hrEmpAcademicProfileByHRs2 = new HashSet<hrEmpAcademicProfileByHR>();
            this.hrEmpAcademicProfileByHRs3 = new HashSet<hrEmpAcademicProfileByHR>();
            this.hrEmpCourses = new HashSet<hrEmpCours>();
            this.hrEmpDisabilities = new HashSet<hrEmpDisability>();
            this.hrEmpEducations = new HashSet<hrEmpEducation>();
            this.hrEmpFamilyHealthInsurances = new HashSet<hrEmpFamilyHealthInsurance>();
            this.hrEmpFamilyMembers = new HashSet<hrEmpFamilyMember>();
            this.hrEmpLanguages = new HashSet<hrEmpLanguage>();
            this.hrEmpPastEmployements = new HashSet<hrEmpPastEmployement>();
            this.hrEmpSkills = new HashSet<hrEmpSkill>();
            this.hrPeople1 = new HashSet<hrPeople>();
            this.hrWorkingHours = new HashSet<hrWorkingHour>();
            this.plActivities = new HashSet<plActivity>();
            this.sylCourseTeachers = new HashSet<sylCourseTeacher>();
            this.sylSyllabis = new HashSet<sylSyllabi>();
            this.sylSyllabis1 = new HashSet<sylSyllabi>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string EmailAddress { get; set; }
        public string ExtUserName { get; set; }
        public string AccessCardID { get; set; }
        public bool IsAcademician { get; set; }
        public string LSUser { get; set; }
        public string DoorSysID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> Employee_AcademicDepartment { get; set; }
        public Nullable<int> erpAcademicDepartment_hrPerson1 { get; set; }
        public Nullable<int> hrPerson_erpFaculty1 { get; set; }
        public Nullable<int> erpUniversity_hrPerson1 { get; set; }
        public Nullable<int> Employee_Department { get; set; }
        public Nullable<int> hrPerson_hrPerson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erpAcademicDepartment> erpAcademicDepartments { get; set; }
        public virtual erpAcademicDepartment erpAcademicDepartment { get; set; }
        public virtual erpAcademicDepartment erpAcademicDepartment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erpFaculty> erpFaculties { get; set; }
        public virtual erpFaculty erpFaculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erpUniversity> erpUniversities { get; set; }
        public virtual erpUniversity erpUniversity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrAddress> hrAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrDepartment> hrDepartments { get; set; }
        public virtual hrDepartment hrDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmergencyContact> hrEmergencyContacts { get; set; }
        public virtual hrEmpAcademicProfileByAcademician hrEmpAcademicProfileByAcademician { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpAcademicProfileByHR> hrEmpAcademicProfileByHRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpAcademicProfileByHR> hrEmpAcademicProfileByHRs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpAcademicProfileByHR> hrEmpAcademicProfileByHRs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpAcademicProfileByHR> hrEmpAcademicProfileByHRs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpCours> hrEmpCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpDisability> hrEmpDisabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpEducation> hrEmpEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpFamilyHealthInsurance> hrEmpFamilyHealthInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpFamilyMember> hrEmpFamilyMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpLanguage> hrEmpLanguages { get; set; }
        public virtual hrEmpMilService hrEmpMilService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpPastEmployement> hrEmpPastEmployements { get; set; }
        public virtual hrEmpProfile hrEmpProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrEmpSkill> hrEmpSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrPeople> hrPeople1 { get; set; }
        public virtual hrPeople hrPeople2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrWorkingHour> hrWorkingHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plActivity> plActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sylCourseTeacher> sylCourseTeachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sylSyllabi> sylSyllabis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sylSyllabi> sylSyllabis1 { get; set; }
    }
}
