//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VERPSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class sylSyllabi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sylSyllabi()
        {
            this.sylAssesments = new HashSet<sylAssesment>();
            this.sylCourseMaterials = new HashSet<sylCourseMaterial>();
            this.sylCourseTeachers = new HashSet<sylCourseTeacher>();
            this.sylLearningOutcomes = new HashSet<sylLearningOutcome>();
            this.sylPrerequisites = new HashSet<sylPrerequisite>();
            this.sylSyllabusNotesSets = new HashSet<sylSyllabusNotesSet>();
            this.sylSyllabusTeachingMethods = new HashSet<sylSyllabusTeachingMethod>();
            this.sylWorkloadStructures = new HashSet<sylWorkloadStructure>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string AcademicYear { get; set; }
        public string Language { get; set; }
        public string Objective { get; set; }
        public string Criteria { get; set; }
        public int ECTSCredits { get; set; }
        public int MinWorkloadHours { get; set; }
        public int MaxWorkloadHours { get; set; }
        public System.DateTime PreparationDate { get; set; }
        public string Status { get; set; }
        public string WFUser { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public byte[] RowVersion { get; set; }
        public int Syllabus_AcademicDepartment { get; set; }
        public int Syllabus_Employee { get; set; }
        public Nullable<int> sylSyllabus_hrPerson1 { get; set; }
        public int Syllabus_Course { get; set; }
    
        public virtual erpAcademicDepartment erpAcademicDepartment { get; set; }
        public virtual hrPeople hrPeople { get; set; }
        public virtual hrPeople hrPeople1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sylAssesment> sylAssesments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sylCourseMaterial> sylCourseMaterials { get; set; }
        public virtual sylCours sylCours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sylCourseTeacher> sylCourseTeachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sylLearningOutcome> sylLearningOutcomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sylPrerequisite> sylPrerequisites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sylSyllabusNotesSet> sylSyllabusNotesSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sylSyllabusTeachingMethod> sylSyllabusTeachingMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sylWorkloadStructure> sylWorkloadStructures { get; set; }
    }
}
