//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VERPSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class sylWorkloadStructure
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public double ContactHours { get; set; }
        public double NonContactHours { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public byte[] RowVersion { get; set; }
        public int WorkloadStructure_Syllabus { get; set; }
        public int sylWorkloadStructure_sylTeachingMethod { get; set; }
    
        public virtual sylSyllabi sylSyllabi { get; set; }
        public virtual sylTeachingMethod sylTeachingMethod { get; set; }
    }
}
