//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VERPSWeb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwWHheader
    {
        public string Id { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public int RecYear { get; set; }
        public int RecMonth { get; set; }
        public Nullable<int> AWH { get; set; }
        public string TotalWorkingTime { get; set; }
        public string TimeDiff { get; set; }
        public string TotalOvertime { get; set; }
    }
}
