//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWin1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HR1Entities : DbContext
    {
        public HR1Entities()
            : base("name=HR1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DoorsRawData> DoorsRawDatas { get; set; }
        public virtual DbSet<vw1> vw1 { get; set; }
        public virtual DbSet<vwDoorTime> vwDoorTimes { get; set; }
        public virtual DbSet<vwMax> vwMaxes { get; set; }
        public virtual DbSet<vwMin> vwMins { get; set; }
        public virtual DbSet<vwWorkingTime> vwWorkingTimes { get; set; }
    }
}
