//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWin1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw1
    {
        public int ID { get; set; }
        public System.DateTime Eventdatetime { get; set; }
        public Nullable<System.DateTime> EventdatetimeUTC { get; set; }
        public Nullable<short> OperationID { get; set; }
        public Nullable<short> Isexit { get; set; }
        public string Operationdescription { get; set; }
        public Nullable<short> Usertype { get; set; }
        public string Username { get; set; }
        public string UserExtID { get; set; }
        public string UserGPF1 { get; set; }
        public string UserGPF2 { get; set; }
        public string UserGPF3 { get; set; }
        public string UserGPF4 { get; set; }
        public string UserGPF5 { get; set; }
        public string Cardserialnumber { get; set; }
        public string CardID { get; set; }
        public string Doorname { get; set; }
        public string DoorExtID { get; set; }
        public string DoorGPF1 { get; set; }
        public string DoorGPF2 { get; set; }
        public Nullable<System.DateTime> EventDay { get; set; }
    }
}
