//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWin1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMax
    {
        public Nullable<System.DateTime> EventTime { get; set; }
        public string CardID { get; set; }
        public Nullable<System.DateTime> EventDay { get; set; }
    }
}
