//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWin1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwWorkingTime
    {
        public Nullable<System.DateTime> EntryTime { get; set; }
        public Nullable<System.DateTime> ExitTime { get; set; }
        public string CardID { get; set; }
        public Nullable<System.DateTime> EventDay { get; set; }
        public Nullable<int> TotalHours { get; set; }
        public Nullable<int> TotalMinutes { get; set; }
        public Nullable<int> AndMinutes { get; set; }
        public Nullable<int> WorkingHours { get; set; }
        public Nullable<int> WorkingMinutes { get; set; }
        public Nullable<int> HourDiff { get; set; }
        public Nullable<int> MinuteDiff { get; set; }
        public Nullable<int> RecYear { get; set; }
        public Nullable<int> RecMonth { get; set; }
        public Nullable<int> RecDay { get; set; }
    }
}
